root_dir = fileparts(mfilename("fullpath"));
addpath(root_dir);
cfg = core.ProjectConfig.load(reload=true);

core.ComsolLivelinkModeler.ensure_ready( ...
    host=cfg.comsol.host, ...
    port=cfg.comsol.port, ...
    comsol_root=cfg.comsol.root, ...
    connect=true);

import com.comsol.model.util.*
disp("COMSOL LiveLink initialized. ModelUtil is ready.");
