import core.*
import types.*
import primitives.*
import ops.*

% Example 6: MSQ3 membrane-chip geometry (fully inline implementation).
ctx = GeometryPipeline.with_shared_comsol(enable_comsol=false, ...
                                         enable_gds=true, ...
                                         comsol_api="mph", ...
                                         preview_klayout=true, ...
                                         snap_on_grid=false,...
                                         gds_resolution_nm=1,...
                                         warn_on_snap=true, ...
                                         reset_model=true);

ctx.add_layer("backside", gds_layer=10, gds_datatype=0, comsol_workplane="wp1", ...
    comsol_selection="backside_opening", comsol_selection_state="all");
ctx.add_layer("membrane", gds_layer=11, gds_datatype=0, comsol_workplane="wp1", ...
    comsol_selection="membrane", comsol_selection_state="all");
ctx.add_layer("front_sin", gds_layer=13, gds_datatype=0, comsol_workplane="wp1", ...
    comsol_selection="front_sin", comsol_selection_state="all");
ctx.add_layer("front_al", gds_layer=33, gds_datatype=0, comsol_workplane="wp1", ...
    comsol_selection="front_al", comsol_selection_state="all");

% Base unit helper for vertex coordinates expressed in um.
p_um = Parameter(1, "ex6_u", unit="um");

% Parameters (matching MSQ3 YAML values).
p_chip_w = Parameter(6000, "ex6_chip_w", unit="um");
p_chip_h = Parameter(6000, "ex6_chip_h", unit="um");
p_mem_off_x = Parameter(1000, "ex6_mem_off_x", unit="um"); % 1 mm
p_mem_off_y = Parameter(0, "ex6_mem_off_y", unit="um");
p_mem_w = Parameter(140, "ex6_mem_w", unit="um");
p_mem_h = Parameter(110, "ex6_mem_h", unit="um");

p_wafer_thk = Parameter(280, "ex6_wafer_thk", unit="um");
p_tan_etch = Parameter(1.412, "ex6_tan_etch", unit="", auto_register=false);
p_overetch = Parameter(8, "ex6_overetch", unit="um");

p_koh_margin = Parameter(40, "ex6_koh_margin", unit="um");
p_koh_corner = Parameter(40, "ex6_koh_corner", unit="um");

p_al_margin = Parameter(10, "ex6_al_margin", unit="um");
p_bias_dist = Parameter(90, "ex6_bias_dist", unit="um");
p_bias_w = Parameter(100, "ex6_bias_w", unit="um");
p_bias_h = Parameter(100, "ex6_bias_h", unit="um");
p_bias_conn_w = Parameter(20, "ex6_bias_conn_w", unit="um");

p_pillar_size = Parameter(300, "ex6_pillar_size", unit="um");
p_pillar_loc_x = Parameter(700, "ex6_pillar_loc_x", unit="um");
p_pillar_loc_y = Parameter(700, "ex6_pillar_loc_y", unit="um");

% Geometry derivation (all scalar values below in um).
chip_center_um = [0, 0];
mem_center_um = chip_center_um + [p_mem_off_x.value, p_mem_off_y.value];
back_extra_um = 2 * p_wafer_thk.value / p_tan_etch.value - 2 * p_overetch.value;
back_w_um = p_mem_w.value + back_extra_um;
back_h_um = p_mem_h.value + back_extra_um;

al_w_um = p_mem_w.value - 2 * p_al_margin.value;
al_h_um = p_mem_h.value - 2 * p_al_margin.value;
bias_pad_loc_x_um = al_w_um / 2 + p_bias_dist.value + p_bias_w.value / 2;

koh_center_um = mem_center_um + [0.5 * (p_bias_dist.value - p_al_margin.value + p_bias_w.value), 0];
koh_w_um = p_mem_w.value - p_al_margin.value + p_bias_dist.value + p_bias_w.value + 2 * p_koh_margin.value;
koh_h_um = p_mem_h.value + 2 * p_koh_margin.value;

% Membrane and backside opening.
membrane = Rectangle(...
    center=Vertices(mem_center_um, p_um), ...
    width=p_mem_w, height=p_mem_h, layer="membrane"); %#ok<NASGU>
backside = Rectangle( ...
    center=Vertices(mem_center_um, p_um), ...
    width=Parameter(back_w_um, "ex6_back_w", unit="um"), ...
    height=Parameter(back_h_um, "ex6_back_h", unit="um"), ...
    layer="backside"); %#ok<NASGU>

% Aluminium frontside pattern (inner rectangle + bias pad + connector).
al_inside = Rectangle(ctx, ...
    center=Vertices(mem_center_um, p_um), ...
    width=Parameter(al_w_um, "ex6_al_w", unit="um"), ...
    height=Parameter(al_h_um, "ex6_al_h", unit="um"), ...
    layer="front_al");
bias_pad = Rectangle(ctx, ...
    center=Vertices(mem_center_um + [bias_pad_loc_x_um, 0], p_um), ...
    width=p_bias_w, height=p_bias_h, layer="front_al");
al_connector = Rectangle(ctx, ...
    center=Vertices(mem_center_um + [0.5 * bias_pad_loc_x_um, 0], p_um), ...
    width=Parameter(bias_pad_loc_x_um, "ex6_bias_con_len", unit="um"), ...
    height=p_bias_conn_w, layer="front_al");
al_layer = Union(ctx, {al_inside, bias_pad, al_connector}, layer="front_al"); %#ok<NASGU>

% KOH protection (main rectangle + 4 corner blocks).
koh_main = Rectangle(ctx, ...
    center=Vertices(koh_center_um, p_um), ...
    width=Parameter(koh_w_um, "ex6_koh_w", unit="um"), ...
    height=Parameter(koh_h_um, "ex6_koh_h", unit="um"), ...
    layer="front_sin");
koh_corner_seed = Rectangle(ctx, ...
    center=Vertices(koh_center_um + [-0.5 * koh_w_um, -0.5 * koh_h_um], p_um), ...
    width=p_koh_corner, height=p_koh_corner, layer="front_sin");
koh_corners = Array2D(ctx, koh_corner_seed, ncopies_x=2, ncopies_y=2, ...
    delta_x=Vertices([koh_w_um, 0], p_um), delta_y=Vertices([0, koh_h_um], p_um), ...
    layer="front_sin");
koh_layer = Union(ctx, {koh_main, koh_corners}, layer="front_sin");

% Four pillars (+ optional local corner-protection blocks).
pillar_seed_center_um = mem_center_um + [-p_pillar_loc_x.value, -p_pillar_loc_y.value];
pillar_seed = Rectangle(ctx, center=Vertices(pillar_seed_center_um, p_um), ...
    width=p_pillar_size, height=p_pillar_size, layer="front_sin");
pillar_corner_seed = Rectangle(ctx, ...
    center=Vertices(pillar_seed_center_um + [-0.5 * p_pillar_size.value, -0.5 * p_pillar_size.value], p_um), ...
    width=p_koh_corner, height=p_koh_corner, layer="front_sin");
pillar_corners = Array2D(ctx, pillar_corner_seed, ncopies_x=2, ncopies_y=2, ...
    delta_x=Vertices([p_pillar_size.value, 0], p_um), ...
    delta_y=Vertices([0, p_pillar_size.value], p_um), ...
    layer="front_sin");
pillar_template = Union(ctx, {pillar_seed, pillar_corners}, layer="front_sin");
pillars_layer = Array2D(ctx, pillar_template, ncopies_x=2, ncopies_y=2, ...
    delta_x=Vertices([2 * p_pillar_loc_x.value, 0], p_um), ...
    delta_y=Vertices([0, 2 * p_pillar_loc_y.value], p_um), ...
    layer="front_sin");

% Frontside SiN negative mask: chip rectangle minus positive SIN pattern.
sin_positive = Union(ctx, {koh_layer, pillars_layer}, layer="front_sin");
chip_rect = Rectangle(ctx, center=Vertices(chip_center_um, p_um), ...
    width=p_chip_w, height=p_chip_h, layer="front_sin");
sin_negative = Difference(ctx, chip_rect, {sin_positive}, layer="front_sin"); %#ok<NASGU>

fprintf("Example 6 membrane center: [%.3f, %.3f] um\n", ...
    mem_center_um(1), mem_center_um(2));
fprintf("Example 6 backside opening dims: [%.3f, %.3f] um\n", ...
    back_w_um, back_h_um);
fprintf("Example 6 KOH protection dims: [%.3f, %.3f] um\n", ...
    koh_w_um, koh_h_um);

ctx.build();
