import core.*
import types.*
import primitives.*
import ops.*
import routing.*

% Example 5: routed multi-track cable between two ports using +routing.
ctx = GeometrySession.with_shared_comsol(use_comsol=true, use_gds=true, ...
    comsol_api="mph", ...
    preview_klayout=true, preview_scope="final", preview_step_delay_s=0.08, ...
    snap_on_grid=false, gds_resolution_nm=1, warn_on_snap=true, ...
    reset_model=true, clean_on_reset=false);

ctx.add_layer("metal1", gds_layer=1, gds_datatype=0, comsol_workplane="wp1", ...
    comsol_selection="metal1", comsol_selection_state="all", emit_to_comsol=true);
ctx.add_layer("gap", gds_layer=2, gds_datatype=0, comsol_workplane="wp1", ...
    comsol_selection="gap", comsol_selection_state="all", emit_to_comsol=true);

% Base unit helper (all geometry lengths in um).
p_um = Parameter(1, "u_ex5", unit="um");
p_pad_w = Parameter(90, "ex5_pad_w", unit="um");
p_pad_h = Parameter(70, "ex5_pad_h", unit="um");
p_fillet = Parameter(25, "ex5_fillet", unit="um");
p_straight = Parameter(40, "ex5_straight", unit="um");

% Two simple pads to anchor the route visually.
Rectangle(center=Vertices([-260, 0], p_um), width=p_pad_w, height=p_pad_h, ...
    layer="metal1");
Rectangle(center=Vertices([260, 70], p_um), width=p_pad_w, height=p_pad_h, ...
    layer="metal1");

% CPW-like cross section (signal + gap) carried by PortSpec.
cpw = PortSpec( ...
    widths={Parameter(14, "cpw_sig_w", unit="um"), Parameter(34, "cpw_gap_w", unit="um")}, ...
    offsets={0, 0}, ...
    layers=["metal1", "gap"], ...
    subnames=["sig", "gap"]);

pin = PortRef(name="in", pos=Vertices([-210, 0], p_um), ori=[1, 0], spec=cpw);
pout = PortRef(name="out", pos=Vertices([210, 70], p_um), ori=[1, 0], spec=cpw);

feed = Cable(ctx, pin, pout, ...
    name="feedline", ...
    fillet=p_fillet, ...
    start_straight=p_straight, ...
    bend="auto", ...
    ends="straight", ...
    merge_per_layer=true);

fprintf("example_5 feedline length: %.3f um\n", feed.length_nm() / 1000);

ctx.export_gds("example_5.gds");
ctx.build_comsol();
ctx.build_report();
