function out = connect_auto(ctx, port_in, port_out, opts)
arguments
    ctx core.GeometryPipeline
    port_in routing.PortRef
    port_out routing.PortRef
    opts.name {mustBeTextScalar} = "conn_auto_0"
    opts.fillet = 0
    opts.start_straight = 0
    opts.end_straight = []
    opts.bend {mustBeTextScalar} = "auto"
    opts.allow_mismatch logical = false
    opts.adaptor routing.AdaptorSpec = routing.AdaptorSpec()
    opts.meander routing.MeanderSpec = routing.MeanderSpec.disabled()
    opts.target routing.TargetLengthSpec = routing.TargetLengthSpec.disabled()
    opts.layer_override = []
    opts.merge_per_layer logical = true
    opts.ends {mustBeTextScalar} = "straight"
    opts.convexcorner {mustBeTextScalar} = "fillet"
end

out = routing.connect(ctx, port_in, port_out, ...
    name=opts.name, mode="auto", ...
    fillet=opts.fillet, ...
    start_straight=opts.start_straight, ...
    end_straight=opts.end_straight, ...
    bend=opts.bend, ...
    allow_mismatch=opts.allow_mismatch, ...
    adaptor=opts.adaptor, ...
    meander=opts.meander, ...
    target=opts.target, ...
    layer_override=opts.layer_override, ...
    merge_per_layer=opts.merge_per_layer, ...
    ends=opts.ends, ...
    convexcorner=opts.convexcorner);
end
