function out = meander_line(ctx, p1, p2, opts)
arguments
    ctx core.GeometrySession
    p1 routing.PortRef
    p2 routing.PortRef
    opts.name {mustBeTextScalar} = "cpw_meander_0"
    opts.fillet = 0
    opts.target_nm double = NaN
    opts.segment_indices double = []
    opts.amplitude_nm double = 100
    opts.pitch_nm double = 140
    opts.count double = 4
end

m = routing.MeanderSpec( ...
    enabled=true, ...
    segment_indices=opts.segment_indices, ...
    amplitude_nm=opts.amplitude_nm, ...
    pitch_nm=opts.pitch_nm, ...
    count=opts.count);
t = routing.TargetLengthSpec(enabled=isfinite(opts.target_nm), length_nm=opts.target_nm);

out = routing.connect(ctx, p1, p2, ...
    name=opts.name, ...
    fillet=opts.fillet, ...
    meander=m, ...
    target=t);
end
